// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYgIvF2_WaZ13w6xp5BCXRHd3WWOiAWY',
    appId: '1:856075441732:web:bc21d35ced675b870f8e11',
    messagingSenderId: '856075441732',
    projectId: 'carecircle-59586',
    authDomain: 'carecircle-59586.firebaseapp.com',
    storageBucket: 'carecircle-59586.appspot.com',
    measurementId: 'G-PPKTWFKZVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMwZlB3tOviq5uGr-dktU1IVBzpw-DG-g',
    appId: '1:856075441732:android:74aca4260a2dabf70f8e11',
    messagingSenderId: '856075441732',
    projectId: 'carecircle-59586',
    storageBucket: 'carecircle-59586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2Z5tOsKEJWOi8qXtQ5qHEe5Rrjbl_2E',
    appId: '1:856075441732:ios:db9b959330e7b4e60f8e11',
    messagingSenderId: '856075441732',
    projectId: 'carecircle-59586',
    storageBucket: 'carecircle-59586.appspot.com',
    iosBundleId: 'com.example.hackxite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2Z5tOsKEJWOi8qXtQ5qHEe5Rrjbl_2E',
    appId: '1:856075441732:ios:7d9ed0b8c06b6a870f8e11',
    messagingSenderId: '856075441732',
    projectId: 'carecircle-59586',
    storageBucket: 'carecircle-59586.appspot.com',
    iosBundleId: 'com.example.hackxite.RunnerTests',
  );
}
